# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('Avatar', models.ImageField(default='web/static/avatar/default.png', upload_to='web/static/avatar/')),
                ('Name', models.CharField(blank=True, max_length=30)),
                ('Family', models.CharField(blank=True, max_length=30)),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
