# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='CourseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Course'),
        ),
    ]
